// Generated by gencpp from file ins_msg/ImuMsg.msg
// DO NOT EDIT!


#ifndef INS_MSG_MESSAGE_IMUMSG_H
#define INS_MSG_MESSAGE_IMUMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ins_msg
{
template <class ContainerAllocator>
struct ImuMsg_
{
  typedef ImuMsg_<ContainerAllocator> Type;

  ImuMsg_()
    : header()
    , utime(0)
    , acc()
    , gyro()
    , attitude()
    , temperature(0.0)
    , msg_cnt(0)  {
      acc.assign(0.0);

      gyro.assign(0.0);

      attitude.assign(0.0);
  }
  ImuMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , utime(0)
    , acc()
    , gyro()
    , attitude()
    , temperature(0.0)
    , msg_cnt(0)  {
  (void)_alloc;
      acc.assign(0.0);

      gyro.assign(0.0);

      attitude.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _utime_type;
  _utime_type utime;

   typedef boost::array<float, 3>  _acc_type;
  _acc_type acc;

   typedef boost::array<float, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<float, 3>  _attitude_type;
  _attitude_type attitude;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _msg_cnt_type;
  _msg_cnt_type msg_cnt;





  typedef boost::shared_ptr< ::ins_msg::ImuMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_msg::ImuMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ImuMsg_

typedef ::ins_msg::ImuMsg_<std::allocator<void> > ImuMsg;

typedef boost::shared_ptr< ::ins_msg::ImuMsg > ImuMsgPtr;
typedef boost::shared_ptr< ::ins_msg::ImuMsg const> ImuMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_msg::ImuMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_msg::ImuMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_msg::ImuMsg_<ContainerAllocator1> & lhs, const ::ins_msg::ImuMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.utime == rhs.utime &&
    lhs.acc == rhs.acc &&
    lhs.gyro == rhs.gyro &&
    lhs.attitude == rhs.attitude &&
    lhs.temperature == rhs.temperature &&
    lhs.msg_cnt == rhs.msg_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_msg::ImuMsg_<ContainerAllocator1> & lhs, const ::ins_msg::ImuMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ins_msg::ImuMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_msg::ImuMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::ImuMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::ImuMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::ImuMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::ImuMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_msg::ImuMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4240c38970ed6906c83192bcdfb45a79";
  }

  static const char* value(const ::ins_msg::ImuMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4240c38970ed6906ULL;
  static const uint64_t static_value2 = 0xc83192bcdfb45a79ULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_msg::ImuMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_msg/ImuMsg";
  }

  static const char* value(const ::ins_msg::ImuMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_msg::ImuMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 utime\n"
"float32[3] acc\n"
"float32[3] gyro\n"
"float32[3] attitude\n"
"float32 temperature\n"
"uint8 msg_cnt\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ins_msg::ImuMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_msg::ImuMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.utime);
      stream.next(m.acc);
      stream.next(m.gyro);
      stream.next(m.attitude);
      stream.next(m.temperature);
      stream.next(m.msg_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_msg::ImuMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_msg::ImuMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "utime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.utime);
    s << indent << "acc[]" << std::endl;
    for (size_t i = 0; i < v.acc.size(); ++i)
    {
      s << indent << "  acc[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acc[i]);
    }
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "attitude[]" << std::endl;
    for (size_t i = 0; i < v.attitude.size(); ++i)
    {
      s << indent << "  attitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.attitude[i]);
    }
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "msg_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_MSG_MESSAGE_IMUMSG_H
