// Generated by gencpp from file ins_msg/MagMsg.msg
// DO NOT EDIT!


#ifndef INS_MSG_MESSAGE_MAGMSG_H
#define INS_MSG_MESSAGE_MAGMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ins_msg
{
template <class ContainerAllocator>
struct MagMsg_
{
  typedef MagMsg_<ContainerAllocator> Type;

  MagMsg_()
    : header()
    , utime(0)
    , mag()
    , msg_cnt(0)  {
      mag.assign(0.0);
  }
  MagMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , utime(0)
    , mag()
    , msg_cnt(0)  {
  (void)_alloc;
      mag.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _utime_type;
  _utime_type utime;

   typedef boost::array<float, 3>  _mag_type;
  _mag_type mag;

   typedef uint8_t _msg_cnt_type;
  _msg_cnt_type msg_cnt;





  typedef boost::shared_ptr< ::ins_msg::MagMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_msg::MagMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MagMsg_

typedef ::ins_msg::MagMsg_<std::allocator<void> > MagMsg;

typedef boost::shared_ptr< ::ins_msg::MagMsg > MagMsgPtr;
typedef boost::shared_ptr< ::ins_msg::MagMsg const> MagMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_msg::MagMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_msg::MagMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_msg::MagMsg_<ContainerAllocator1> & lhs, const ::ins_msg::MagMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.utime == rhs.utime &&
    lhs.mag == rhs.mag &&
    lhs.msg_cnt == rhs.msg_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_msg::MagMsg_<ContainerAllocator1> & lhs, const ::ins_msg::MagMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ins_msg::MagMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_msg::MagMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::MagMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::MagMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::MagMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::MagMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_msg::MagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bee64c96ada223eec16e97374109c1f";
  }

  static const char* value(const ::ins_msg::MagMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bee64c96ada223eULL;
  static const uint64_t static_value2 = 0xec16e97374109c1fULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_msg::MagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_msg/MagMsg";
  }

  static const char* value(const ::ins_msg::MagMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_msg::MagMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 utime\n"
"float32[3] mag\n"
"\n"
"uint8 msg_cnt\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ins_msg::MagMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_msg::MagMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.utime);
      stream.next(m.mag);
      stream.next(m.msg_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_msg::MagMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_msg::MagMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "utime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.utime);
    s << indent << "mag[]" << std::endl;
    for (size_t i = 0; i < v.mag.size(); ++i)
    {
      s << indent << "  mag[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mag[i]);
    }
    s << indent << "msg_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_MSG_MESSAGE_MAGMSG_H
