// Generated by gencpp from file ins_msg/OdomMsg.msg
// DO NOT EDIT!


#ifndef INS_MSG_MESSAGE_ODOMMSG_H
#define INS_MSG_MESSAGE_ODOMMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ins_msg
{
template <class ContainerAllocator>
struct OdomMsg_
{
  typedef OdomMsg_<ContainerAllocator> Type;

  OdomMsg_()
    : header()
    , utime(0)
    , pulse_cnt(0.0)
    , speed(0.0)
    , msg_cnt(0)  {
    }
  OdomMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , utime(0)
    , pulse_cnt(0.0)
    , speed(0.0)
    , msg_cnt(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _utime_type;
  _utime_type utime;

   typedef float _pulse_cnt_type;
  _pulse_cnt_type pulse_cnt;

   typedef float _speed_type;
  _speed_type speed;

   typedef uint8_t _msg_cnt_type;
  _msg_cnt_type msg_cnt;





  typedef boost::shared_ptr< ::ins_msg::OdomMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_msg::OdomMsg_<ContainerAllocator> const> ConstPtr;

}; // struct OdomMsg_

typedef ::ins_msg::OdomMsg_<std::allocator<void> > OdomMsg;

typedef boost::shared_ptr< ::ins_msg::OdomMsg > OdomMsgPtr;
typedef boost::shared_ptr< ::ins_msg::OdomMsg const> OdomMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_msg::OdomMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_msg::OdomMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_msg::OdomMsg_<ContainerAllocator1> & lhs, const ::ins_msg::OdomMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.utime == rhs.utime &&
    lhs.pulse_cnt == rhs.pulse_cnt &&
    lhs.speed == rhs.speed &&
    lhs.msg_cnt == rhs.msg_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_msg::OdomMsg_<ContainerAllocator1> & lhs, const ::ins_msg::OdomMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ins_msg::OdomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_msg::OdomMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::OdomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::OdomMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::OdomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::OdomMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_msg::OdomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88e4a3d41ea05a905c3200bd7c3d7905";
  }

  static const char* value(const ::ins_msg::OdomMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88e4a3d41ea05a90ULL;
  static const uint64_t static_value2 = 0x5c3200bd7c3d7905ULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_msg::OdomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_msg/OdomMsg";
  }

  static const char* value(const ::ins_msg::OdomMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_msg::OdomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 utime\n"
"\n"
"float32 pulse_cnt\n"
"float32 speed\n"
"\n"
"uint8 msg_cnt\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ins_msg::OdomMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_msg::OdomMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.utime);
      stream.next(m.pulse_cnt);
      stream.next(m.speed);
      stream.next(m.msg_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdomMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_msg::OdomMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_msg::OdomMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "utime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.utime);
    s << indent << "pulse_cnt: ";
    Printer<float>::stream(s, indent + "  ", v.pulse_cnt);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "msg_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_MSG_MESSAGE_ODOMMSG_H
