// Generated by gencpp from file ins_msg/UwbAoaMsg.msg
// DO NOT EDIT!


#ifndef INS_MSG_MESSAGE_UWBAOAMSG_H
#define INS_MSG_MESSAGE_UWBAOAMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ins_msg/PairMeass.h>

namespace ins_msg
{
template <class ContainerAllocator>
struct UwbAoaMsg_
{
  typedef UwbAoaMsg_<ContainerAllocator> Type;

  UwbAoaMsg_()
    : header()
    , utime(0)
    , dev_id(0)
    , pair_meass()
    , status(0)
    , msg_cnt(0)  {
    }
  UwbAoaMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , utime(0)
    , dev_id(0)
    , pair_meass()
    , status(0)
    , msg_cnt(0)  {
  (void)_alloc;
      pair_meass.assign( ::ins_msg::PairMeass_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _utime_type;
  _utime_type utime;

   typedef uint32_t _dev_id_type;
  _dev_id_type dev_id;

   typedef boost::array< ::ins_msg::PairMeass_<ContainerAllocator> , 19>  _pair_meass_type;
  _pair_meass_type pair_meass;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _msg_cnt_type;
  _msg_cnt_type msg_cnt;





  typedef boost::shared_ptr< ::ins_msg::UwbAoaMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_msg::UwbAoaMsg_<ContainerAllocator> const> ConstPtr;

}; // struct UwbAoaMsg_

typedef ::ins_msg::UwbAoaMsg_<std::allocator<void> > UwbAoaMsg;

typedef boost::shared_ptr< ::ins_msg::UwbAoaMsg > UwbAoaMsgPtr;
typedef boost::shared_ptr< ::ins_msg::UwbAoaMsg const> UwbAoaMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_msg::UwbAoaMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_msg::UwbAoaMsg_<ContainerAllocator1> & lhs, const ::ins_msg::UwbAoaMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.utime == rhs.utime &&
    lhs.dev_id == rhs.dev_id &&
    lhs.pair_meass == rhs.pair_meass &&
    lhs.status == rhs.status &&
    lhs.msg_cnt == rhs.msg_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_msg::UwbAoaMsg_<ContainerAllocator1> & lhs, const ::ins_msg::UwbAoaMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_msg::UwbAoaMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::UwbAoaMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::UwbAoaMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38d0a653ce9de672e25f5c2f6393f060";
  }

  static const char* value(const ::ins_msg::UwbAoaMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38d0a653ce9de672ULL;
  static const uint64_t static_value2 = 0xe25f5c2f6393f060ULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_msg/UwbAoaMsg";
  }

  static const char* value(const ::ins_msg::UwbAoaMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64       utime\n"
"\n"
"uint32      dev_id\n"
"\n"
"PairMeass[19] pair_meass\n"
"\n"
"uint8       status\n"
"uint8       msg_cnt\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ins_msg/PairMeass\n"
"\n"
"uint16      swarm_id\n"
"uint8       node_id\n"
"uint8       los_flag\n"
"uint64[2]   stamps\n"
"\n"
"uint16      distance\n"
"int16       aoa\n"
"int16       pdoa1\n"
"int16       pdoa2\n"
"\n"
;
  }

  static const char* value(const ::ins_msg::UwbAoaMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.utime);
      stream.next(m.dev_id);
      stream.next(m.pair_meass);
      stream.next(m.status);
      stream.next(m.msg_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UwbAoaMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_msg::UwbAoaMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_msg::UwbAoaMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "utime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.utime);
    s << indent << "dev_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dev_id);
    s << indent << "pair_meass[]" << std::endl;
    for (size_t i = 0; i < v.pair_meass.size(); ++i)
    {
      s << indent << "  pair_meass[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ins_msg::PairMeass_<ContainerAllocator> >::stream(s, indent + "    ", v.pair_meass[i]);
    }
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "msg_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_MSG_MESSAGE_UWBAOAMSG_H
