// Generated by gencpp from file ins_msg/UwbPosDownMsg.msg
// DO NOT EDIT!


#ifndef INS_MSG_MESSAGE_UWBPOSDOWNMSG_H
#define INS_MSG_MESSAGE_UWBPOSDOWNMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ins_msg/UwbPos.h>

namespace ins_msg
{
template <class ContainerAllocator>
struct UwbPosDownMsg_
{
  typedef UwbPosDownMsg_<ContainerAllocator> Type;

  UwbPosDownMsg_()
    : header()
    , utime(0)
    , uwb_poss()
    , status(0)
    , msg_cnt(0)  {
    }
  UwbPosDownMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , utime(0)
    , uwb_poss(_alloc)
    , status(0)
    , msg_cnt(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _utime_type;
  _utime_type utime;

   typedef  ::ins_msg::UwbPos_<ContainerAllocator>  _uwb_poss_type;
  _uwb_poss_type uwb_poss;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _msg_cnt_type;
  _msg_cnt_type msg_cnt;





  typedef boost::shared_ptr< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> const> ConstPtr;

}; // struct UwbPosDownMsg_

typedef ::ins_msg::UwbPosDownMsg_<std::allocator<void> > UwbPosDownMsg;

typedef boost::shared_ptr< ::ins_msg::UwbPosDownMsg > UwbPosDownMsgPtr;
typedef boost::shared_ptr< ::ins_msg::UwbPosDownMsg const> UwbPosDownMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ins_msg::UwbPosDownMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ins_msg::UwbPosDownMsg_<ContainerAllocator1> & lhs, const ::ins_msg::UwbPosDownMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.utime == rhs.utime &&
    lhs.uwb_poss == rhs.uwb_poss &&
    lhs.status == rhs.status &&
    lhs.msg_cnt == rhs.msg_cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ins_msg::UwbPosDownMsg_<ContainerAllocator1> & lhs, const ::ins_msg::UwbPosDownMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ins_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "005914774339b077b09ea7254ee22520";
  }

  static const char* value(const ::ins_msg::UwbPosDownMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x005914774339b077ULL;
  static const uint64_t static_value2 = 0xb09ea7254ee22520ULL;
};

template<class ContainerAllocator>
struct DataType< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ins_msg/UwbPosDownMsg";
  }

  static const char* value(const ::ins_msg::UwbPosDownMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64       utime\n"
"\n"
"UwbPos      uwb_poss\n"
"\n"
"uint8       status\n"
"uint8       msg_cnt\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ins_msg/UwbPos\n"
"uint32     dev_id\n"
"float32[3] pos\n"
"float32[6] cov\n"
;
  }

  static const char* value(const ::ins_msg::UwbPosDownMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.utime);
      stream.next(m.uwb_poss);
      stream.next(m.status);
      stream.next(m.msg_cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UwbPosDownMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ins_msg::UwbPosDownMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ins_msg::UwbPosDownMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "utime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.utime);
    s << indent << "uwb_poss: ";
    s << std::endl;
    Printer< ::ins_msg::UwbPos_<ContainerAllocator> >::stream(s, indent + "  ", v.uwb_poss);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "msg_cnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INS_MSG_MESSAGE_UWBPOSDOWNMSG_H
