(cl:in-package ins_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          UTIME-VAL
          UTIME
          REF-VAL
          REF
          OBS-VAL
          OBS
          OUT-VAL
          OUT
          STATE_RPY-VAL
          STATE_RPY
          STATE_VEL-VAL
          STATE_VEL
          STATE_POS-VAL
          STATE_POS
          STATE_GYRO_BIAS-VAL
          STATE_GYRO_BIAS
          STATE_ACC_BIAS-VAL
          STATE_ACC_BIAS
          STATE_SCALE-VAL
          STATE_SCALE
          STATE_YAW_ERROR-VAL
          STATE_YAW_ERROR
          STATE_PITCH_ERROR-VAL
          STATE_PITCH_ERROR
          INNOV_SPEED-VAL
          INNOV_SPEED
          INNOV_RTK_POS-VAL
          INNOV_RTK_POS
          INNOV_RTK_VEL-VAL
          INNOV_RTK_VEL
          INNOV_RTK_HDG-VAL
          INNOV_RTK_HDG
          R_SPEED-VAL
          R_SPEED
          R_RTK_POS-VAL
          R_RTK_POS
          R_RTK_VEL-VAL
          R_RTK_VEL
          R_RTK_HDG-VAL
          R_RTK_HDG
          P-VAL
          P
          SPEED_IMU_TIME-VAL
          SPEED_IMU_TIME
          SPEED_RTK_TIME-VAL
          SPEED_RTK_TIME
          DELTA_IMU_TIME-VAL
          DELTA_IMU_TIME
          MSG_CNT-VAL
          MSG_CNT
))