(cl:in-package ins_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          UTIME-VAL
          UTIME
          POS_TYPE-VAL
          POS_TYPE
          MEAS_ENABLE-VAL
          MEAS_ENABLE
          GNSS_MASK-VAL
          GNSS_MASK
          ANT_NUM-VAL
          ANT_NUM
          SV_NUM_TRACKED-VAL
          SV_NUM_TRACKED
          SV_NUM_USED-VAL
          SV_NUM_USED
          DIFF_AGE-VAL
          DIFF_AGE
          SOL_AGE-VAL
          SOL_AGE
          MS-VAL
          MS
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          HEADING-VAL
          HEADING
          STD_LONGITUDE-VAL
          STD_LONGITUDE
          STD_LATITUDE-VAL
          STD_LATITUDE
          STD_HEIGHT-VAL
          STD_HEIGHT
          STD_VE-VAL
          STD_VE
          STD_VN-VAL
          STD_VN
          STD_VU-VAL
          STD_VU
          STD_ROLL-VAL
          STD_ROLL
          STD_PITCH-VAL
          STD_PITCH
          STD_HEADING-VAL
          STD_HEADING
          UNDULATION-VAL
          UNDULATION
          BASELINE_LENGTH-VAL
          BASELINE_LENGTH
          CHAN_VALID-VAL
          CHAN_VALID
          CHAN_SVID-VAL
          CHAN_SVID
          CHAN_PLLLOCK-VAL
          CHAN_PLLLOCK
          CHAN_CN0-VAL
          CHAN_CN0
          CHAN_PSEUDORANGE-VAL
          CHAN_PSEUDORANGE
          CHAN_CARRPHASE-VAL
          CHAN_CARRPHASE
          MSG_CNT-VAL
          MSG_CNT
))